GitHub action demo (#10)

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -6,7 +6,7 @@
 # separate terms of service, privacy policy, and support
 # documentation.
 
-name: Java CI with Maven
+name: Java Application Pipeline
 
 on:
   push:
@@ -17,20 +17,88 @@ on:
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
-
+    outputs:
+      tag-version: ${{ steps.set-version.outputs.new_tag }}
     steps:
-    - uses: actions/checkout@v4
-    - name: Set up JDK 17
-      uses: actions/setup-java@v4
-      with:
-        java-version: '17'
-        distribution: 'temurin'
-        cache: maven
-    - name: Build with Maven
-      run: mvn -B package --file pom.xml
+      - name: Checkout
+        uses: actions/checkout@v3
+      - name: Bump version
+        id: set-version
+        uses: anothrNick/github-tag-action@1.71.0
+        env:
+          WITH_V: true
+          GIT_API_TAGGING: false
+          DRY_RUN: true
+          DEFAULT_BRANCH: master
 
-    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
-    - name: Update dependency graph
-      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
+      - name: output new version
+        run: echo ${{ steps.set-version.outputs.new_tag }}
+
+      - name: Set up JDK 17
+        uses: actions/setup-java@v3
+        with:
+          java-version: '17'
+          distribution: 'temurin'
+          cache: maven
+      - name: Apply new version
+        run: mvn versions:set -DnewVersion=${{ steps.set-version.outputs.new_tag }}
+      - name: Build
+        run: mvn -B package --file pom.xml
+      - name: Publish test report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/target/surefire-reports/TEST-*.xml'
+          include_passed: true
+          detailed_summary: true
+
+      - name: Tag version
+        if: github.ref == 'refs/heads/master'
+        uses: anothrNick/github-tag-action@1.71.0
+        env:
+          WITH_V: true
+          GIT_API_TAGGING: false
+          DRY_RUN: false
+          DEFAULT_BRANCH: master
+
+      - name: Upload artifact
+        if: github.ref == 'refs/heads/master'
+        uses: actions/upload-artifact@v4
+        with:
+          name: my-workspace
+          path: ${{ github.workspace }}/**/*
+
+  build-image:
+    if: github.ref == 'refs/heads/master'
+    needs: build
+    runs-on: ubuntu-latest
+    env:
+      IMAGE_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ needs.build.outputs.tag-version }}
+    steps:
+      - name: Download artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: my-workspace
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+      - name: Login to Docker Hub
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
+      - name: Build and push
+        uses: docker/build-push-action@v6
+        with:
+          push: true
+          context: .
+          file: ${{ github.workspace }}/docker/Dockerfile
+          tags: ${{ env.IMAGE_TAG }}
+
+  deploy:
+    if: github.ref == 'refs/heads/master'
+    needs: build-image
+    runs-on: ubuntu-latest
+    steps:
+      - name: Demo
+        run: echo run deployment command
