updated github action

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -21,7 +21,7 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v3
-      - name: Bump version and push tag
+      - name: Bump version
         id: version
         uses: anothrNick/github-tag-action@v1 # Don't use @master or @v1 unless you're happy to test the latest version
         env:
@@ -29,6 +29,32 @@ jobs:
           DRY_RUN: true
       - name: output
         run: echo ${{ steps.version.outputs.new_tag }}
+      - name: Bump version again
+        id: version
+        uses: anothrNick/github-tag-action@v1 # Don't use @master or @v1 unless you're happy to test the latest version
+        env:
+          WITH_V: true
+          DRY_RUN: true
+      - name: output again
+        run: echo ${{ steps.version.outputs.new_tag }}
+
+#      - name: Set up JDK 17
+#        uses: actions/setup-java@v3
+#        with:
+#          java-version: '17'
+#          distribution: 'temurin'
+#          cache: maven
+#      - name: Update version
+#        run: mvn versions:set -DnewVersion=${{ steps.version.outputs.new_tag }}
+#      - name: Build with Maven
+#        run: mvn -B package --file pom.xml
+#      - name: Publish Test Report
+#        uses: mikepenz/action-junit-report@v4
+#        if: success() || failure() # always run even if the previous step fails
+#        with:
+#          report_paths: '**/target/surefire-reports/TEST-*.xml'
+#          include_passed: true
+#          detailed_summary: true
 
 #jobs:
 #  build:
